spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iparhan_blog
    username: root
    password: root

mybatis:
  type-aliases-package: com.iparhan.blog.bean
